# print('I', 'love', 'you', 'too')
# print(100 + 100)
# print(200)
# print('100 + 100 =', 100 + 100)
# name = input('请输入名字:')
# print('Hello', name)
# print 'hellop'
# print('----这是一个两数相乘运算小程序----')
# a = int(input('第一个数：'))
# b = int(input('第二个数：'))
# print(a, '乘以', b, '等于', a * b)
# a = 10
# if a >= 20:
#     print(a)
# else:
#     print(-a)
# print('Google')
# print("I'm OK")
# print('I\'m OK!')
# print("I'm OK")
# print(r'\\\\t\\')
# print('''line1
# line2
# line3''')
# print(True)
# print(3 > 2)
# print(3 > 5)
# print(True and True)
# print(True and False)
#
# print(not True)
# print(None)
# a = 123
# print(a)
# a = 'nihao'
# print(a)
# print(10 / 3)
# print(9 / 3)
# print(10 // 3)
# print(10 % 3)
# print('n =', 123, '\nf =', 456.789, '\ns1 =', '\'Hello, world\'', '\ns2 =', '\'Hello, \\\'Adam\\\'\'',
#       '\ns3 =', "r\'Hello,", '\"Bart\"\'', '\ns4 =', 'r\'\'\'Hello,\nLisa!\'\'\'')
# print("I'm OK")
# print('中文str')
# print(ord('A'), ord('b'), chr(20013), chr(25991))
# print('\'\u4e2d\u6587\'')
# print('ABC'.encode('ascii'))
# print(len('avc'))
# print('My name is %s,oh nihao %s' % ('Make', 'laozo'))
# print('Hi %s,you have $%d' % ('Tom', 1000))
# print('%.4f' % 3.1415926)
# print('%.d' % 113.1415926)
# print('%2d - %2d' % (3, 1))
# print('My name is %s,\nI \'m %s years old.' % ('Tom', 20))
# print('Hello,{0}\'s grade is {1:.1f}'.format('xiaoming', 100.11))
# print('中文'.encode('gb2312'))
classmates = ['Mack', 'Tom', 'Jack', 'Carol']
print(classmates)
print(len(classmates))
print(classmates[1], classmates[2], classmates[0])
print(classmates[-1])
print(classmates[-2])
print(classmates[-3])
print(classmates[-4])
classmates.append('Adam')
